---
# ansible
ansible_user: root

console_locales: [ 'en_US.UTF-8' ]
console_root_password: '{{ lookup("password", secret + "/credentials/" + ansible_fqdn + "/console/root/password length=" + console_root_password_length) }}'
console_packages: [ 'mc',
                    'htop',
                    'iotop',
                    'sysstat',
                    'screen',
                    'vim',
                    'nload',
                    'aptitude',
                    'tasksel',
                    'p7zip',
                    'lsof',
                    'iftop',
                    'dstat',
                    'iozone3' ]
core_packages: "{{console_packages}}"
#debobs.auth
auth_ldap_conf: False
auth_admin_accounts: [ 'ansicon' ]

#debobs.users
users_default:
  - users_ansicon

users_admins:
  - users_ansicon
  - users_le9i0nx

users_ansicon:
  - name:   'ansicon'
    state:  'present'
    group:  'ansicon'
    groups: ['admins']
    shell: '/bin/bash'
    sshkeys:
      - "{{ lookup('file', secret + '/users/ansicon/sshkeys') }}"

users_le9i0nx:
  - name:   'le9i0nx'
    state:  'present'
    group:  'le9i0nx'
    groups: ['sudo','sshusers']
    shell: '/bin/bash'
    update_password: 'always'
    password: "{{ lookup('file', secret + '/users/le9i0nx/password') }}"
    sshkeys:
      - "{{ lookup('file', secret + '/users/le9i0nx/sshkeys') }}"

apt_unattended_upgrades: True

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
