---

#nrpe
nagios_nrpe_server_apt_packages:
  - nagios-nrpe-server
  - nagios-plugins-standard
  - nagios-plugins-contrib
  - libnagios-plugin-perl
icinga_pool: ['192.168.0.8']
nagios_nrpe_server_pool: "{{icinga_pool + ['127.0.0.1']}}"
nagios_nrpe_allow: "{{nagios_nrpe_server_pool}}"
nagios_nrpe_server_config:
  server_port: 5666
  allowed_hosts: "{{ nagios_nrpe_server_pool | join(',')}}"
  dont_blame_nrpe: 1
nagios_nrpe_server_commands: "{{ nagios_nrpe_server_commands_default + nagios_nrpe_server_commands_cups }}"

nagios_nrpe_server_commands_cups:
  - {name: "check_cups_queue", plugin: "check_cups_queue", args: "-H localhost -T b -w 10 -c 50 -a 1" }

#bacula
bacula__conf_client_job:

  - {name: "etc", JobDefs: "GateBackup", Schedule: "Daily_0" }

icinga__client:
  group: "{{ ansible_domain.split('.')[0] }}"
  name: '{{ ansible_hostname }}'
  ip: '{{ ansible_fqdn }}'
  parents: "{{ icinga__client_parents_rugion }}"
  hostgroups: "{{ icinga__client_hostgroups_default + icinga__client_hostgroups_cups + icinga__client_hostgroups_rugion }}"

icinga__client_hostgroups_cups:
  - "nrpe_cups_queue"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
