---

#nrpe
nagios_nrpe_server_apt_packages:
  - nagios-nrpe-server
  - nagios-plugins-standard
  - nagios-plugins-contrib
  - libnagios-plugin-perl
icinga_pool: ['192.168.0.8']
nagios_nrpe_server_pool: "{{icinga_pool + ['127.0.0.1']}}"
nagios_nrpe_allow: "{{nagios_nrpe_server_pool}}"
nagios_nrpe_server_config:
  server_port: 5666
  allowed_hosts: "{{ nagios_nrpe_server_pool | join(',')}}"
  dont_blame_nrpe: 1
nagios_nrpe_server_commands:
  - {name: "check_disk", plugin: "check_disk", args: "-w 20% -c 5%",sudo: true }
  - {name: "check_total_procs", plugin: "check_procs", args: "-w 1600 -c 1800", sudo: true }
  - {name: "check_apt", plugin: "check_apt" }
  - {name: "check_ntp", plugin: "check_ntp", args: "-H localhost -w -1:1 -c -2:2"}
  - {name: "check_service", plugin: "check_procs", args: "-w $ARG2$ -c $ARG3$ -a \"$ARG1$\"", sudo: true }
  - {name: "check_mem", plugin: "check_mem.pl", args: "-w 10 -c 5 -f -C"}
  - {name: "check_iftraffic", plugin: "check_iftraffic_nrpe.py", args: "-i" }
  - {name: "check_cups_queue", plugin: "check_cups_queue", args: "-H localhost -T b -w 10 -c 50 -a 1" }

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
