---

bacula__conf_dir:
  name: 'backup'
  name_ansible: 'backup.74ru.mpautina.ru'
  ip:
    - "192.168.0.19"

bacula__conf_sd:
  name: 'backup'
  name_ansible: 'backup.74ru.mpautina.ru'
  device_path: "/mnt/storage/bacula"
  ip:
    - "192.168.0.19"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
