---

#nagios_nrpe_server_config
#nagios_nrpe_server_apt_packages_group: []
#nagios_nrpe_server_commands_group: []
#icinga__client_hostgroups_group: []

bind__conf_d_default:

  - name: "hfm.ru"
    type: "forward"
    forward: [ "172.28.90.10" ]

  - name: "rn"
    type: "forward"
    forward: [ "192.168.80.1" ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
