---
ferm_ansible_controllers: ['0.0.0.0/0']
tcpwrappers_ansible_controllers: ['ALL']
console_issue: 'Org. le9i0nx.ru'
#grub
grub_cmd_elevator: 'noop'
#tinc
tinc_network: 'mesh0'
tinc_inventory_hosts: '{{ groups.homes }}'
tinc_interface: '{{ tinc_network }}'
tinc_connection_type: 'static'
tinc_ifupdown_interface:
  - iface: '{{ tinc_interface }}'
    type: 'interface'
    inet: '{{ tinc_connection_type }}'
    auto: '{{ tinc_interface_auto }}'
    addresses: '{{ tinc_host_addr }}'
    force: True

users_default:
  - users_ansicon

# syncthing
role_syncthing_user: 'le9i0nx'
role_syncthing:
  inventory_hosts: '{{ groups.homes }}'
  folders:
    path: '/home/le9i0nx/crypt/'
    id: 'crypt'

# avahi
avachi_ferm_interface:
  - '{{tinc_interface}}'

# debops.apt
apt_unattended_upgrades_repositories:
  - "origin=Debian,codename={{ apt_sources_release }},label=Debian-Security"
  - "o=Debian,a={{ apt_sources_release }}"
  - "o=Debian,a={{ apt_sources_release_updates }}"
  - "o=Syncthing"

apt_sources_release: 'stable'
apt_unattended_upgrades: True
apt_sources_release_list:
  - '{{ apt_sources_release }}'
  - '{{ apt_sources_release_updates }}'
  - 'testing'
  - 'unstable'
  - 'experimental'

apt_preferences_list:
  - package: '*'
    pin: 'release unstable'
    priority: '50'
    filename: "unstable"
  - package: '*'
    pin: 'release testing'
    priority: '60'
    filename: "testing"
  - package: '*'
    pin: 'release experimental'
    priority: '40'
    filename: "experimental"



## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
