---

#nrpe
nagios_nrpe_server_apt_packages_group: []
nagios_nrpe_server_commands_group: []
icinga__client_hostgroups_group:
  - "jabber"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
