---

# ferm
ferm__ansible_controllers:  "{{admin_allow_pool}}"
#tcpwrappers_ansible_controllers: "{{admin_allow_pool}}"
console_issue: 'Org. 74.ru'

#apt
unattended_upgrades__enabled: False

#grub
grub_cmd_elevator: 'noop'

#ssh
sshd__ferm_limit: True
sshd__password_authentication: 'yes'
sshd__permit_root_login: 'yes'

users_root:
  - name:   'root'
    state:  'present'
    group:  'root'
    password: "{{ lookup('file', secret + '/users/root/'+ ansible_default_ipv4.network + '/password') }}"
    sshkeys:
      - "{{ lookup('file', secret + '/users/root/sshkeys') }}"
      - "{{ lookup('file', secret + '/users/root/sshkeys2') }}"

console_root_password: "{{ lookup('file', secret + '/users/root/' + ansible_default_ipv4.network + '/password') }}"

users_ansicon:
  - name:   'ansicon'
    state:  'present'
    group:  'ansicon'
    groups: ['admins']
    shell: '/bin/bash'
    sshkeys:
      - "{{ lookup('file', secret + '/users/ansicon/sshkeys') }}"
      - "{{ lookup('file', secret + '/users/ansicon/sshkeys2') }}"

users_edi:
  - name:   'edi'
    state:  'present'
    group:  'edi'
    groups: ['sudo','sshusers']
    gid:    512
    uid:    512
    shell: '/bin/bash'
    password: "{{ lookup('file', secret + '/users/edi/password') }}"
    update_password: 'on_create'

users_pavlov:
  - name:   'pavlov'
    state:  'present'
    group:  'edi'
    groups: ['sudo','sshusers']
    shell: '/bin/bash'
    password: "{{ lookup('file', secret + '/users/pavlov/password') }}"
    update_password: 'on_create'

users_ngs:
  - name:   'ngs'
    state:  'present'
    group:  'ngs'
    groups: ['admins']
    shell: '/bin/bash'
    password: "{{ lookup('file', secret + '/users/ngs/password') }}"

users_default:
  - '{{ users_ansicon }}'

users_admins:
  - '{{ users_ansicon }}'
  - '{{ users_le9i0nx }}'
  - '{{ users_edi }}'
  - '{{ users_root }}'
  - '{{ users_pavlov }}'
  - '{{ users_ngs }}'

office_chelyabinsk_rodnik_pool:
  - '195.206.240.34'
  - '94.181.33.105'
office_chelyabinsk_lesopark_pool:
  - '193.138.129.118'
  - '95.78.171.64'
office_02_pool:
  - '195.151.45.169' # 02 corp.ufa1.ru
office_29_pool:
  - '212.14.179.26'  # 29 corp.29.ru
office_34_pool:
  - '213.234.16.19'  # 34 corp.v1.ru
office_59_pool:
#  - '178.161.209.39' # 59 info59.ru
  - '46.146.205.197' # 59 info59.ru
office_61_pool:
  - '86.110.189.141'  # 61 corp.161.ru
office_63_pool:
  - '195.151.37.217' # 63 info63.ru
office_72_pool:
  - '212.76.162.201' # 72 ig72.ru
office_74_pool: "{{office_chelyabinsk_rodnik_pool + office_chelyabinsk_lesopark_pool}}" #74 info74.ru
office_76_pool:
  - '176.214.79.10'  # 76 corp.76.ru

admin_allow_pool: "{{office_74_pool + [ '192.168.0.0/23' ]}}"

#nagios_nrpe_server_config
icinga_pool:
  - '192.168.0.8'

icinga__server:
  name_ansible: "icinga.74ru.mpautina.ru"
  ip: "{{ icinga_pool }}"

nagios_nrpe_server_apt_packages:
  - '{{ nagios_nrpe_server_apt_packages_default if nagios_nrpe_server_apt_packages_default|d() else [] }}'
  - '{{ nagios_nrpe_server_apt_packages_group if nagios_nrpe_server_apt_packages_group|d() else [] }}'

nagios_nrpe_server_apt_packages_default:
  - '{{ "nagios-plugins-extra" if ( ansible_distribution == "Ubuntu" ) else [] }}'
  - "nagios-nrpe-server"
  - "nagios-plugins-standard"
  - "nagios-plugins-contrib"
  - "libnagios-plugin-perl"
  - "ntpdate"

nagios_nrpe_server_pool: "{{icinga_pool + ['127.0.0.1']}}"
nagios_nrpe_allow: "{{nagios_nrpe_server_pool}}"
nagios_nrpe_server_config:
  server_port: 5666
  allowed_hosts: "{{ nagios_nrpe_server_pool | join(',')}}"
  dont_blame_nrpe: 1
nagios_nrpe_server_commands: "{{ nagios_nrpe_server_commands_group + nagios_nrpe_server_commands_default }}"

nagios_nrpe_server_commands_default:
  - {name: "check_disk", plugin: "check_disk", args: "-w 20% -c 5%", sudo: true }
  - {name: "check_total_procs", plugin: "check_procs", args: "-w 1600 -c 1800", sudo: true }
  - {name: "check_apt", plugin: "check_apt" }
  - {name: "check_ntp", plugin: "check_ntp", args: "-H localhost -w -1:1 -c -2:2"}
  - {name: "check_ntpdate", plugin: "check_ntpdate.py"}
  - {name: "check_service", plugin: "check_procs", args: "-w $ARG2$ -c $ARG3$ -a \"$ARG1$\"", sudo: true }
  - {name: "check_mem", plugin: "check_mem.pl", args: "-w 10 -c 5 -f -C"}
  - {name: "check_iftraffic", plugin: "check_iftraffic_nrpe.py", args: "-i" }
  - {name: "check_uptime", plugin: "check_uptime" }
  - {name: "check_mio_sda", plugin: "check_mio", args: "-d sda -w 500,30000,52428800,52428800 -c 600,40000,104857600,104857600"}
  - {name: "check_mio_sdb", plugin: "check_mio", args: "-d sdb -w 500,30000,52428800,52428800 -c 600,40000,104857600,104857600"}

icinga__client_parents: "{{ icinga__client_parents_rugion }}"
icinga__client_hostgroups: "{{ icinga__client_hostgroups_default + icinga__client_hostgroups_group + icinga__client_hostgroups_rugion }}"

icinga__client_hostgroups_default:
  - "ssh"
  - "nrpe"
  - "nrpe_apt"
  - "nrpe_space"
  - "nrpe_mem"
  - "nrpe_traffic"
  - "nrpe_ntpdate"
  - "nrpe_mio_sda"

#bacula
bacula__conf_client_job_default:
  - {name: "etc", JobDefs: "etc", Schedule: "Daily_0" }
bacula__conf_client_jobDefs_default:
  - {name: "etc", Schedule: "Daily_0", FileSet: "etc-set" }
bacula__conf_client_FileSet_default:
  - {name: "etc-set", File: [
      "/etc",
      "/var/spool/cron",
      "/usr/local/bin",
      ] }

# nginx
nginx_server_default:
  enabled: False
  name: [ ]

#ntp
ntp__ignore_ntpdate: True
ntp__servers: [ 'pool.ntp.org',
                '192.168.0.7',
                '0.europe.pool.ntp.org',
                '0.asia.pool.ntp.org',
                '1.europe.pool.ntp.org',
                '1.debian.pool.ntp.org' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
