---

# ferm
ferm__enabled: False

# samba
samba__service_name: 'smbd'
samba__default_homes: []
samba__default_shares: []

samba__default_global:

  # hacing nt4
  client_ntlmv2_auth: 'no'
  require_strong_key: 'no'
  allow_nt4_crypto: 'yes'
  smb2_leases: 'yes'

  wins_server: '{{ samba__wins_server }}'
  dns_proxy: 'no'
  panic_action: '/usr/share/samba/panic-action %d'

  # ldap
  passdb_backend: 'ldapsam:ldap://127.0.0.1/'
  ldap_suffix: '{{ samba__ldap_suffix }}'
  ldap_user_suffix: 'ou=users'
  ldap_group_suffix: 'ou=groups'
  ldap_machine_suffix: 'ou=computers'
  ldap_admin_dn: '"cn=admin,dc=rugion,dc=ru"'
  ldap_delete_dn: 'no'
  ldap_ssl: 'off'
  ldap_passwd_sync: 'yes'
  idmap_gid: '10000-30000'
  idmap_uid: '10000-30000'


  obey_pam_restrictions: 'yes'
  unix_password_sync: 'yes'

  passwd_program: '/usr/bin/passwd %u'
  passwd_chat: '*Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .'

  pam_password_change: 'yes'
  logon_script: '\\PDC\netlogon\logon.bat'
  template_shell: '/bin/bash'
  usershare_allow_guests: 'yes'
  logon_path: ''
  logon_home: ''


  # Browsing / Identification
  workgroup: '{{ samba__workgroup | default("WORKGROUP") }}'
  server_string: '{{ samba__server_string | default("%h file server") }}'
  server_role: 'classic backup domain controller'

  # Logs / Accounting
  log_file: '/var/log/samba/log.%m'
  max_log_size: '1000'
  syslog: '0'


  invalid_users: 'root bin daemon adm sync shutdown halt mail news uucp proxy www-data backup sshd'
  map_to_guest: 'Bad User'
  guest_account: 'nobody'

  # File system / Directories
  unix_charset: 'UTF8'
  locking: 'yes'
  dont_descend: './lost+found'
  use_sendfile: 'yes'
  hide_unreadable: 'yes'
  hide_files: '/.*/lost+found/'


  # Disable printing by default
  printing: 'bsd'
  load_printers: 'no'
  printcap_name: '/dev/null'
  show_add_printer_wizard: 'no'
  disable_spoolss: 'yes'

#nrpe
nagios_nrpe_server_apt_packages:
  - nagios-nrpe-server
  - nagios-plugins-standard
  - nagios-plugins-contrib
  - libnagios-plugin-perl
icinga_pool: ['192.168.0.8']
nagios_nrpe_server_pool: "{{icinga_pool + ['127.0.0.1']}}"
nagios_nrpe_allow: "{{nagios_nrpe_server_pool}}"
nagios_nrpe_server_config:
  server_port: 5666
  allowed_hosts: "{{ nagios_nrpe_server_pool | join(',')}}"
  dont_blame_nrpe: 1
nagios_nrpe_server_commands:
  - {name: "check_disk", plugin: "check_disk", args: "-w 20% -c 5%",sudo: true }
  - {name: "check_total_procs", plugin: "check_procs", args: "-w 1600 -c 1800", sudo: true }
  - {name: "check_apt", plugin: "check_apt" }
  - {name: "check_ntp", plugin: "check_ntp", args: "-H localhost -w -1:1 -c -2:2"}
  - {name: "check_service", plugin: "check_procs", args: "-w $ARG2$ -c $ARG3$ -a \"$ARG1$\"", sudo: true }
  - {name: "check_raid", plugin: "check_raid", sudo: true }
  - {name: "check_mem", plugin: "check_mem.pl", args: "-w 10 -c 5 -f -C"}
  - {name: "check_iftraffic", plugin: "check_iftraffic_nrpe.py", args: "-i" }

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
