---

dependencies:

  - role: debops.secret

  - role: debops.ferm
    tags:
      - 'depend::ferm'
      - 'depend::ferm:bacula_storage'
      - 'depend-of::bacula_storage'
      - 'type::dependency'
    ferm_dependent_rules:
      - '{{ bacula_storage__ferm__dependent_rules }}'

  - role: debops.apt_preferences
    tags:
      - 'depend::apt_preferences'
      - 'depend::apt_preferences:bacula_storage'
      - 'depend-of::bacula_storage'
      - 'type::dependency'
    apt_preferences__group_list:
      - '{{ bacula_storage__apt_preferences__dependent_list }}'
    when: ((ansible_distribution == 'Ubuntu') and
           (ansible_distribution_major_version == '16' ))

  - role: debops.apt
    tags:
      - 'depend::apt'
      - 'depend::apt:bacula_storage'
      - 'depend-of::bacula_storage'
      - 'type::dependency'
    apt__host_repositories:
      - '{{ bacula_storage__apt__repositories }}'
    when: ((ansible_distribution == 'Ubuntu') and
           (ansible_distribution_major_version == '16' ))


galaxy_info:
  author: 'Aleksej Gavrilov'
  description: 'Configure bacula storage packages'
  license: 'GPLv3'
  min_ansible_version: '2.0.0'
  platforms:
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - trusty
  categories:
    - system
    - backup

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
