---

- name: copy conf vim
  copy: src=./vimrc.local dest=/etc/vim/vimrc.local owner=root group=root mode=0444

- name: set vim default editor
  alternatives: name=editor path=/usr/bin/vim.basic

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
