---

#mail_info74_ru_ssl_crt: '{{pki_path}}/certs/mail.info74.ru.crt'
#mail_info74_ru_ssl_key: '{{pki_path}}/private/mail.info74.ru.key'
#imap_info74_ru_ssl_crt: '{{pki_path}}/certs/imap.info74.ru.crt'
#imap_info74_ru_ssl_key: '{{pki_path}}/private/imap.info74.ru.key'
#pop3_info74_ru_ssl_crt: '{{nginx_pki_path}}/certs/pop3.info74.ru.crt'
#pop3_info74_ru_ssl_key: '{{nginx_pki_path}}/private/pop3.info74.ru.key'
#smtp_info74_ru_ssl_crt: '{{nginx_pki_path}}/certs/smtp.info74.ru.crt'
#smtp_info74_ru_ssl_key: '{{nginx_pki_path}}/private/smtp.info74.ru.key'

#mail_116_ru_ssl_crt: '{{nginx_pki_path}}/certs/mail.corp.116.ru.crt'
#mail_116_ru_ssl_key: '{{nginx_pki_path}}/private/mail.corp.116.ru.key'
#pop3_116_ru_ssl_crt: '{{nginx_pki_path}}/certs/pop3.corp.116.ru.crt'
#pop3_116_ru_ssl_key: '{{nginx_pki_path}}/private/pop3.corp.116.ru.key'
#smtp_116_ru_ssl_crt: '{{nginx_pki_path}}/certs/smtp.corp.116.ru.crt'
#smtp_116_ru_ssl_key: '{{nginx_pki_path}}/private/smtp.corp.116.ru.key'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
