---

- hosts: all
  become_user: root
  become: False

  roles: # Блок ролей, у нас пока одна роль
    - debops.auth
    - debops.users

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
