---

postfixadmin_packages: [  'dbconfig-common', 'postfixadmin' ]


# Should postfixadmin role manage its own dependencies?
postfixadmin_dependencies: True

# What subdomain should be used for postfixadmin in nginx configuration
#postfixadmin_domain: [ 'postfixadmin.{{ ansible_domain }}' ]
postfixadmin_domain: [ 'postfixadmin.{{ ansible_fqdn }}' ]

# Default length of generated passwords
password_length: '20'

# Default postfixadmin control password
postfixadmin_control_password: "{{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/mysql/postfixadmin/password length=' + password_length) }}"

postfixadmin_control_user: 'postfixadmin'
postfixadmin_control_database: 'postfixadmin'
postfixadmin_dbtype: 'mysqli'

# List of IP addresses or network ranges in CIDR format, allowed to access
# postfixadmin. Leave empty to allow access from all IP addresses/networks
postfixadmin_allow: []

# Max upload size for nginx and php5
postfixadmin_upload_size: '64M'

# Maximum number of PHP5 processes for postfixadmin
postfixadmin_php5_max_children: '20'


postfixadmin_default_language: 'ru'
postfixadmin_postfix_admin_url: '/'
postfixadmin_domain_path: 'YES'
postfixadmin_domain_in_mailbox: 'NO'

postfixadmin_nginx_server:
  by_role: 'le90nx.postfixadmin'
  enabled: True
  default: False
#  listen: ['80','[::]:80']
  type: 'php5'
  name: '{{ postfixadmin_domain }}'
  root: '/usr/share/postfixadmin'

  options: |
    client_max_body_size  {{ postfixadmin_upload_size }};

  location:

    # Required for location_allow to work
    '/': 'try_files $uri $uri/ =404;'

  location_allow:
    '/': '{{ postfixadmin_allow }}'

  php5: 'php5_postfixadmin'

  php5_options: |
    {% if postfixadmin_allow is defined and postfixadmin_allow %}
    {% for address in postfixadmin_allow %}
    allow {{ address }};
    {% endfor %}
    deny all;
    {% endif %}

postfixadmin_nginx_upstream_php5:
  enabled: True
  name: 'php5_postfixadmin'
  type: 'php5'
  php5: 'postfixadmin'

postfixadmin_php5_pool:
  enabled: True
  name: 'postfixadmin'
  user: 'www-data'
  group: 'www-data'
  pm_max_children: '{{ postfixadmin_php5_max_children }}'
  php_value:
    post_max_size: '{{ postfixadmin_upload_size }}'
    upload_max_filesize: '{{ postfixadmin_upload_size }}'


