---

samba__default_shares:
  'netlogon':
    path: '{{ samba__path }}/netlogon'
    comment: 'netlogon share'
    guest_ok: 'no'
    write_list: '@nt_admin'
    read_list: '@nt_users'

    read_only: 'No'
    create_mask: '0660'
    directory_mask: '0770'
    inherit_owner: 'yes'
    inherit_acls: 'yes'
    inherit_permissions: 'yes'
    map_acl_inherit: 'yes'
    locking: 'no'

  'tosha':
    path: '{{ samba__path }}/economists'
    comment: 'economists share'
    guest_ok: 'no'
#    writable: 'yes'
    write_list: '@nt_admin, @nt_economists'
    read_list: '@nt_admin, @nt_economists'
#    create_mode: '660'
#    directory_mode: '770'

    read_only: 'No'
  # маска для создаваемых файлов
    create_mask: '0660'
  # маска для создаваемых директорий
    directory_mask: '0770'
  # наследовать владельца (вышестоящей директории)
    inherit_owner: 'yes'
  # наследовать ACL 
    inherit_acls: 'yes'
  # наследовать права
    inherit_permissions: 'yes'
  # позвоялет редактору прав из винды корректно обрабатывать
  # наследуемые права
    map_acl_inherit: 'yes'
  # блокировки - иногда бывают грабли без этого пункта
    locking: 'no'

samba__global_custom:
  wins_server: "192.168.0.7"

icinga__client_name: "tosha"
#bacula
bacula__conf_client:
  name: '{{ icinga__client_name }}'
  passwd: '{{ bacula__gen_client_password }}'

#bacula
bacula__conf_client_job_host:
  - {name: "samba", JobDefs: "samba", Schedule: "Daily_0" }
bacula__conf_client_jobDefs_host:
  - {name: "samba", Schedule: "Daily_0", FileSet: "samba-set" }
bacula__conf_client_FileSet_host:
  - {name: "samba-set", File: [
      "/srv/samba",
      ] }


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
