---
ferm_ansible_controllers:  "{{admin_allow_pool +
  ['0.0.0.0/0']}}"
tcpwrappers_ansible_controllers: "{{admin_allow_pool + ['ALL']}}"

mail_domain:
  - {domain: 'info74.ru',ou: 'chelyabinsk'}
  - {domain: 'info63.ru',ou: 'samara'}
  - {domain: 'info59.ru',ou: 'perm'}
  - {domain: 'corp.161.ru',ou: 'rostov'}
  - {domain: 'corp.ufa1.ru',ou: 'ufa'}
  - {domain: 'corp.76.ru',ou: 'yaroslavl'}
  - {domain: 'ig72.ru',ou: 'tumen'}
  - {domain: 'corp.v1.ru',ou: 'volgograd'}
  - {domain: 'corp.29.ru',ou: 'arkhangelsk'}


#ntp
ntp__timezone: 'Asia/Yekaterinburg'

#ssh
sshd__ferm_limit: 'false'
sshd__PasswordAuthentication: 'yes'
sshd__permit_root_login: 'without-password'

#postfixadmin
postfixadmin_postfix_admin_url: 'https://mail.info74.ru/postfixadmin'
postfixadmin_control_database: 'postfixadmin'

#ldap_server_pool: "edu.rugion.ru"
ldap_server_pool: "localhost"
pki_path: '/srv/pki'

#nginx
nginx_acme_domain: 'mail.info74.ru'
nginx_pki_path: '/etc/nginx/ssl'
nginx_pki_realm: '.'
nginx_server_default:
  enabled: False
  name: [ ]

#dovecot
dovecot_db_name: '{{postfixadmin_control_database}}'
dovecot_ssl_cert: '/etc/dovecot/ssl/mail.info74.ru/fullchain.pem'
dovecot_ssl_key: '/etc/dovecot/ssl/mail.info74.ru/privkey.pem'

#exim
exim_list_dnsbl:
  - 'zen.spamhaus.org'
#  - 'dbl.spamhaus.org/$sender_address_domain'
#  - 'xbl.spamhaus.org'
  - 'relay.mail-abuse.org'
  - 'bl.spamcop.net'
#  - 'relays.ordb.org'
  - 'smtp.dnsbl.sorbs.net'
  - 'recent.dnsbl.sorbs.net'
  - 'recent.spam.dnsbl.sorbs.net'
  - 'dns.rfc-ignorant.org'
  - 'b.barracudacentral.org'
  - 'dnsbl.inps.de'
  - 'ips.backscatterer.org'
  - 'psbl.surriel.com'
  - 'sbl.spamhaus.org'
  - 'dnsbl-1.uceprotect.net'
  - 'dnsbl-3.uceprotect.net'
  - 'db.wpbl.info'

exim_domain: 'info74.ru'
exim_white_list_local_hosts_add:
  - '212.57.190.166' # host.mpautina.ru
  - '195.19.70.10' # office.ngs.ru
  - '213.247.165.202' # hsmedia.ru
  - '89.249.27.230' # hsmedia.ru
  - '176.9.151.116' # sfa.w.rugion.ru
  - '178.161.173.194' # permrc.magnit.ru # убрать после переписки конфига
  - '195.93.186.211' # noreply@ngs.ru
  - '89.237.54.190' # 222-2-222.ru
  - '77.41.165.78'  # 222-2-222.ru

exim_list_dkim:
  - { domain: {'yahoo.com','rambler.ru'} }
  - { domain: {'yandex.ru'}, ip: '{{ exim_list_yandex }}' }
  - { domain: {'gmail.com','googlemail.com','google.com'}, ip: '{{ exim_list_google }}' }
  - { domain: {'mail.ru','inbox.ru','list.ru','bk.ru'}, ip: '{{ exim_list_mail_ru }}' }

exim_list_yandex:
  - '213.180.223.192/26'
  - '37.9.109.0/24'
  - '37.140.128.0/18'
  - '5.45.192.0/19'
  - '5.255.192.0/18'
  - '77.88.0.0/18'
  - '84.201.128.0/18'
  - '87.250.224.0/19'
  - '93.158.136.48/28'
  - '95.108.130.0/23'
  - '95.108.192.0/18'
  - '141.8.132.0/24'

exim_list_google:
  - '64.18.0.0/20'
  - '64.233.160.0/19'
  - '66.102.0.0/20'
  - '66.249.80.0/20'
  - '72.14.192.0/18'
  - '74.125.0.0/16'
  - '108.177.8.0/21'
  - '173.194.0.0/16'
  - '207.126.144.0/20'
  - '209.85.128.0/17'
  - '216.58.192.0/19'
  - '216.239.32.0/19'

exim_list_mail_ru:
  - '94.100.176.0/20'
  - '217.69.128.0/20'
  - '128.140.168.0/21'
  - '188.93.58.0/24'
  - '195.211.128.0/22'
  - '188.93.59.0/24'
  - '128.140.170.0/24'
  - '178.22.92.0/23'
  - '185.5.136.0/22'
  - '5.61.237.0/26'
  - '5.61.237.128/25'
  - '5.61.236.0/24'
  - '87.229.222.66' # mail.betapress.ru мудаки шлют почту от reclamapress@INBOX.ru через себя

exim_list_protection_outlook_com:
  - '207.46.101.128/26'
  - '207.46.108.0/25'
  - '207.46.100.0/24'
  - '207.46.163.0/24'
  - '65.55.169.0/24'
  - '157.55.133.0/25'
  - '157.56.110.0/23'
  - '157.55.234.0/24'
  - '213.199.154.0/24'
  - '213.199.180.0/24'
  - '157.56.120.0/25'
  - '157.56.116.0/25'
  - '157.56.112.0/24'
  - '134.170.140.0/24'
  - '134.170.132.0/24'
  - '207.46.51.64/26'
  - '157.55.158.0/23'
  - '157.56.87.192/26'
  - '64.4.22.64/26'
  - '23.103.128.0/19'
  - '23.103.198.0/23'
  - '65.55.88.0/24'
  - '104.47.0.0/17'
  - '23.103.200.0/21'
  - '23.103.208.0/21'
  - '23.103.191.0/24'
  - '216.32.180.0/23'



exim_white_list_local_hosts: "{{
  office_02_pool +
  office_29_pool +
  office_34_pool +
  office_59_pool +
  office_61_pool +
  office_63_pool +
  office_72_pool +
  office_74_pool +
  office_76_pool +
  exim_white_list_local_hosts_add +
  exim_list_yandex +
  exim_list_google +
  exim_list_mail_ru +
  exim_list_protection_outlook_com
}}"

exim_relay_from_hosts: [
  "193.138.129.118",
  "195.206.240.34",
  "95.78.171.64",
  "94.181.33.105",
  "195.54.18.0/24",
  "195.226.222.0/24",
  "176.56.23.64/27",
  ]
exim_db_name: '{{postfixadmin_control_database}}'
exim_ssl_cert: '{{pki_path}}/certs/smtp.info74.ru.crt'
exim_ssl_key: '{{pki_path}}/private/smtp.info74.ru.key'
exim_pki: '{{pki_path}}'
exim_ldap_server: '{{ldap_server_pool}}'
exim_ldap_server_port: "389"
exim_ldap_aliases: "{{ mail_domain }}"

#roundcube
roundcube_db_name: 'roundcube_121'
roundcube_ldap_server: '{{ldap_server_pool}}'

mysql_mysqld_max_connections: 200
mysql_mysqld_options: {
  'tmp_table_size': '256M',
  'max_heap_table_size': '256M',
  'key_buffer_size': '20M',
  'max_allowed_packet': '1M',
  'table_open_cache': '800',
  'sort_buffer_size': '2M',
  'read_buffer_size': '2M',
  'read_rnd_buffer_size': '8M',
  'myisam_sort_buffer_size': '64M',
  'thread_cache_size': '8',
  'query_cache_size': '64M',
  'thread_concurrency': '4',
  'query_cache_limit': '2M',
  # логгируем запросы длиннее 5 секунд
  'long_query_time': '10',
  'log-slow-queries': '/var/log/mysql/mysqld-slow-query.log',
  # логгируем запросы, не использующие индексы
  'log-queries-not-using-indexes': ,
  # innodb оптимизация
  'innodb_file_per_table':'1',
  'innodb_data_file_path':'ibdata1:10M:autoextend',
}
#mailweb
mailweb_domain_www: |
  [{% for item in mail_domain %}'mail.{{ item.domain }}',{% endfor %} ]
mailweb_domain_autoconfig: |
  [{% for item in mail_domain %}'autoconfig.{{ item.domain }}',{% endfor %} ]
web_admin_allow: "{{admin_allow_pool}}"
web_filials_allow: "{{
  office_02_pool +
  office_29_pool +
  office_34_pool +
  office_59_pool +
  office_61_pool +
  office_63_pool +
  office_72_pool +
  office_74_pool +
  office_76_pool
}}"


# smartd
smartd_mail: 'admins@mpautina.ru'
smartd_disks:
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,0', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,1', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,2', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,3', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,4', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,5', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,6', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,7', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,8', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,9', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,10', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/cciss/c0d0', sub: 'cciss,11', s_hour: '01', l_dow: '6', l_hour: '02'  }


#fail2ban
fail2ban_ignoreip: "{{
  exim_white_list_local_hosts +
  exim_relay_from_hosts
}}"
fail2ban_destemail: 'root@info74.ru'
fail2ban_logtarget: 'SYSLOG'

#rspamd
rspamd__password: "q2"
rspamd__conf_d:

  - name: "rbl_exim"
    type: "rbl"
    data: '{{ exim_list_dnsbl }}'

## vim: ft=yaml:foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
