---
ferm_ansible_controllers: ['0.0.0.0/0']
tcpwrappers_ansible_controllers: ['ALL']
console_issue: 'Org. le9i0nx.ru'
#grub
grub_cmd_elevator: 'noop'

users_root:
  - name:   'root'
    state:  'present'
    group:  'root'
    password: "{{ lookup('file', secret + '/users/root/password_home') }}"
    sshkeys:
      - "{{ lookup('file', secret + '/users/root/sshkeys') }}"
      - "{{ lookup('file', secret + '/users/root/sshkeys2') }}"

console_root_password: "{{ lookup('file', secret + '/users/root/password_home') }}"

users_admins:
  - '{{ users_ansicon }}'
  - '{{ users_le9i0nx }}'

# syncthing
syncthing__dependencies_ferm: True
device_moto:
  - id: "H5K4NYU-P64UC3B-ZY6DIU5-RKE4MJS-AMOW2TK-75API3M-7W5FO5Z-QX3LAAR"
    name: "tapik"
device_en:
  - id: "KDZAIGU-WDGEZUI-D674MX7-HKPCXVS-FXLD6L6-E7S2YOE-YP3JKBG-Y2ZGLQB"
    name: "en"

role_syncthing_user: 'le9i0nx'
role_syncthing_data:
#  devices_add:
#    - "{{ device_moto }}"
  folders:
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/crypt/'
      id: 'crypt'
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/moto_e-photos/'
      id: 'moto_e-photos'
      devices_del:
        - "{{ device_en }}"
      devices_add:
        - "{{ device_moto }}"
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/music/'
      id: 'music'
      devices_del:
        - "{{ device_en }}"
      devices_add:
        - "{{ device_moto }}"
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/le9i0nx/money/'
      id: 'money'
      devices_del:
        - "{{ device_en }}"
      devices_add:
        - "{{ device_moto }}"

# avahi
avachi_ferm_interface:
  - '{{ tinc_interface }}'

# debops.unattended_upgrades
unattended_upgrades__enabled: True
unattended_upgrades__security_origins:

  'Debian':
    - "origin=Debian,codename={{ apt__sources_release }},label=Debian-Security"

unattended_upgrades__release_origins:

  'Debian':
    - "o=Debian,a={{ apt__sources_release }}"
    - "o=Debian,a={{ apt__sources_release_updates }}"
    - "o=Syncthing"

# debops.apt
apt__sources_release_updates: '{{ apt__sources_release }}-updates'
apt__sources_release: 'stable'
apt__sources_release_list:
  - '{{ apt__sources_release }}'
  - '{{ apt__sources_release_updates }}'
  - 'testing'
  - 'unstable'
  - 'experimental'

apt_preferences__list:
  - package: '*'
    pin: 'release unstable'
    priority: '50'
    filename: "unstable"
  - package: '*'
    pin: 'release testing'
    priority: '60'
    filename: "testing"
  - package: '*'
    pin: 'release experimental'
    priority: '40'
    filename: "experimental"

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
