---

- name: Install roundcube packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: roundcube_packages
  when: (roundcube_packages is defined and roundcube_packages)

- name: Create database for roundcube
  mysql_db:
    name:   '{{ roundcube_db_name | default("roundcube") }}'
    state:  'present'
  register: roundcube_database

#- name: Create db schema roundcube
#  mysql_db:
#    name:     '{{ roundcube_db_name | default("roundcube") }}'
#    state:    'import'
#    target:   '/srv/www/roundcube/SQL/mysql.initial.sql'
#  when: roundcube_database is defined and roundcube_database.changed == True

- name: Create roundcube control user
  mysql_user:
    name:     '{{ roundcube_db_user | default("roundcube") }}'
    state:    'present'
    password: '{{ roundcube_db_pass }}'
    priv:     '{{ roundcube_db_name | default("roundcube") }}.*:ALL'

- name: configure roundcube
  template:
    src:    '{{ item.src }}'
    dest:   '{{ item.dest }}'
    owner:  '{{ item.owner | default("root") }}'
    group:  '{{ item.group | default("root") }}'
    mode:   '{{ item.mode | default("0400") }}'
    backup: 'yes'
  with_items:
#    - { src: 'etc/roundcube/debian-db.php.j2', dest: '/srv/www/roundcube/config/debian-db.php', group: 'www-data' , mode: '0440' }
    - { src: 'usr/local/bin/subscription_mail.py.j2', dest: '/usr/local/bin/subscription_mail.py', mode: '0500' }
#    - { src: 'etc/roundcube/main.inc.php.j2', dest: '/etc/roundcube/main.inc.php', group: 'www-data' , mode: '0440' }
#    - { src: 'etc/dbconfig-common/roundcube.conf.j2', dest: '/etc/dbconfig-common/roundcube.conf' }

- name: add cron job
  cron:
    name:   '{{ item.name }}'
    minute: '{{ item.minute | default("*")}}'
    hour:   '{{ item.hour | default("*")}}'
    user:   '{{ item.user }}'
    job:    '{{ item.job }}'
  with_items:
    - {name: 'subscription_mail', minute: '1', user: 'root', job: '/usr/local/bin/subscription_mail.py' }
    - {name: 'roundcube tmp rm', minute: '20' ,hour: '0', user: 'root', job: "find /var/tmp/roundcube/ -name '*' -mtime +2 | xargs -r rm" }
    - {name: 'roundcube old login user rm', minute: '20' ,hour: '0', user: 'root', job: 'mysql -s -D {{roundcube_db_name}} -e "DELETE FROM users WHERE last_login <= DATE_SUB(NOW(), INTERVAL 360 DAY);"' }

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
