---

- name: Manage bacula
  hosts: [ 'debops_service_bacula' ]
  become: True
  become_method: sudo

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ bacula__ferm_dependent_rules }}'

    - role: le9i0nx.bacula
      tags: [ 'role::bacula' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
