---

- name: bind9 install
  hosts: [ 'debops_service_bind', 'debops_bind' ]
  become: True
  become_method: sudo

  roles:

    - role: debops.secret
      tags: [ 'role::secret' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ bind_ferm_dependent_rules }}'

    - role: le9i0nx.bind
      tags: [ 'role::bind' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
