---

- name: exim install mail_srv
  hosts: [ 'debops_all_hosts', 'debops_service_exim' ]
  become: True

  roles:

    - role: debops.secret

    - role: debops.rsyslog
      rsyslog_pools: [ '{{ rsyslog_pool_exim }}' ]
      rsyslog_pool_exim:
        enabled: True
        name: '03-exim'
        options: |
            $template DynFileEximPanic,"/var/log/%HOSTNAME%/%programname%/panic.%$YEAR%.%$MONTH%.%$DAY%.log"
            if $programname == "exim" and $syslogfacility-text == "mail" and $syslogseverity-text == "alert" then		?DynFileEximPanic
            & stop

            $template DynFileExim,"/var/log/%HOSTNAME%/%programname%/mail.%$YEAR%.%$MONTH%.%$DAY%.log"
            if $programname == "exim" and $syslogfacility-text == "mail" then		?DynFileExim
            & stop

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ exim_ferm_dependent_rules }}'

    - role: le9i0nx.exim4
      tags: [ 'role::exim' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
