---

- name: Manage MariaDB server
  hosts: [ 'debops_service_mariadb_server', 'debops_mariadb_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ mariadb_server__ferm__dependent_rules }}'

    - role: debops.mariadb_server
      tags: [ 'role::mariadb_server' ]


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
