---

- name: ntp
  hosts: [ 'debops_all_hosts', 'debops_service_ntp' ]
  become: True
  become_method: sudo

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ ntp_ferm_dependent_rules }}'

    - role: debops.ntp
      tags: [ 'role::ntp' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
