---

- name: roundcube install
  hosts: [ 'debops_all_hosts', 'debops_service_roundcube' ]
  become: True
  become_method: sudo

  roles:

    - role: le9i0nx.roundcube
      tags: [ 'role::roundcube' ]

    - role: debops.php5
      php5_packages:
        - 'php5-mysql'
        - 'php5'
        - 'php5-ldap'
        - 'php5-mcrypt'
      php5_pools:
        - '{{ mail_php5_pool }}'
      when: mail_dependencies is defined and mail_dependencies
      tags: [ 'role::php5' ]

    - role: debops.nginx
      nginx_servers:
        - '{{mail_info74_ru_nginx_server}}'
        - '{{cap_nginx_server}}'
        - '{{autoconfig_nginx_server}}'
      nginx_upstreams:
        - '{{ mail_nginx_upstream_php5 }}'
      when: mail_dependencies is defined and mail_dependencies
      tags: [ 'role::nginx' ]


    - role: le9i0nx.mailweb
      tags: [ 'role::mailweb' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
