---

- name: Manage Samba service
  hosts: [ 'debops_service_samba', 'debops_samba' ]
  become: True

  roles:

    - role: debops.samba
      tags: [ 'role::samba' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
