---

- name: Manage OpenLDAP service
  hosts: [ 'debops_service_slapd', 'debops_slapd' ]
  become: True

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ slapd_ferm_dependent_rules }}'

    - role: debops.slapd
      tags: [ 'role::slapd' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
