---

- name: squid install
  hosts: [ 'debops_service_squid', 'debops_squid' ]
  become: True
  become_method: sudo

  roles:

    - role: debops.fcgiwrap
      tags: [ 'role::fcgiwrap' ]
      fcgiwrap__instances:
        - '{{ squid__fcgiwrap__instance }}'

    - role: debops.secret
      tags: [ 'role::secret' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ squid__ferm_dependent_rules }}'
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_servers:
        - '{{ wpad__nginx__servers }}'

    - role: le9i0nx.squid
      tags: [ 'role::squid' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
