---

- name: Manage OpenSSH Server
  hosts: [ 'debops_all_hosts', 'debops_service_sshd' ]
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences_dependent_list:
        - '{{ sshd_apt_preferences_dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd_ferm_dependent_rules }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers_dependent_allow:
        - '{{ sshd_tcpwrappers_dependent_allow }}'

    - role: debops.sshd
      tags: [ 'role::sshd' ]
