---

#- name: Test nginx and restart
#  command: nginx -t
#  notify: Restart nginx
#
#- name: Test nginx and reload
#  command: nginx -t
#  notify: Reload nginx

- name: Restart dovecot
  service: name=dovecot state=restarted

- name: Reload dovecot
  service: name=dovecot state=reloaded

