---

dependencies:

  - role: debops.secret

  - role: debops.rsyslog
    rsyslog_pools: [ '{{ rsyslog_pool_roundcube }}' ]
    rsyslog_pool_roundcube:
        enabled: True
        name: '02-roundcube'
        options: |
            $template DynFileRoundcube,"/var/log/%HOSTNAME%/%programname%/%$YEAR%.%$MONTH%.%$DAY%.log"
            if $programname == "roundcube" then ?DynFileRoundcube
            & stop

