---
mail_dependencies: True

password_length: '20'

mailweb_domain_www: []
mailweb_domain_autoconfig: []
web_admin_allow: []
web_filials_allow: []

# Max upload size for nginx and php5
mail_upload_size: '64M'

# Maximum number of PHP5 processes for postfixadmin
mail_php5_max_children: '50'
mail_php5_min_children: '5'

nginx_ssl: True

cap_nginx_server:
  by_role: 'le90nx.mailweb cap'
  enabled: False
  default: True
  listen: ['80 default','[::]:80 default']
  ssl: False
  type: 'default'
  name: [ 'cap','_:)' ]
  options: |
    return      444;


  location:

    # Required for location_allow to work
    '/': |
      return 444;

mail_location_allow:
    '/postfixadmin': '{{ web_admin_allow }}'
    '/userlogos': '{{ web_filials_allow }}'
    '/protected/userlogos': '{{ web_filials_allow }}'
    '/rspamd/': '{{ web_admin_allow }}'

mail_location_php: |
  location ~ ^(?<script_name>.+\.php)$ {
      limit_except GET HEAD POST { deny all; }
      try_files $script_name =404;
      include fastcgi_params;
      fastcgi_index index.php;
      fastcgi_pass php5_mail;
  }
  index index.php;
  location ~ ^(?<script_name>.+\.php)(?<path_info>/.*)$ {
      limit_except GET HEAD POST { deny all; }
      try_files $script_name =404;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$script_name;
      fastcgi_param PATH_INFO $path_info;
      fastcgi_index index.php;
      fastcgi_pass php5_mail;
  }

mail_location:
    '/': 'return 307 https://$host/roundcube;'

    '/postfixadmin': |
      try_files $uri/ /index.php =404;
      {{mail_location_php}}

    '/roundcube': |
      try_files $uri/ /index.php =404;
      {{mail_location_php}}

    '~ /roundcube/(logs|config|temp)': 'deny all;'
    '/logo': ' '
    '/rspamd/': |
      proxy_set_header X-Real-IP  $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass       http://localhost:11334/;
      proxy_redirect   http://localhost:11334/ /rspamd/;

mail_options: |
  client_max_body_size {{ mail_upload_size }};

mail_info74_ru_nginx_server:
  by_role: 'le90nx.mailweb'
  enabled: True
  default: False
  listen: ['80','[::]:80']
  listen_ssl: ['443','[::]:443']
  ssl: True
  name: "{{ mailweb_domain_www }}"
  pki_crt: 'fullchain.pem'
  pki_key: 'privkey.pem'
  pki_trusted: 'chain.pem'
  pki_realm: 'mail.info74.ru'
  root: '/srv/www/sites/mail/public'
  options: "{{mail_options}}"
  location: "{{mail_location}}"
  location_allow: "{{mail_location_allow}}"
  php5: 'php5_mail'

mail_nginx_upstream_php5:
  enabled: True
  name: 'php5_mail'
  type: 'php5'
  php5: 'mail'

mail_php5_pool:
  enabled: True
  name: 'mail'
  user: 'www-data'
  group: 'www-data'
  pm: 'dynamic'
  pm_max_children: '{{ mail_php5_max_children }}'
  pm_min_children: '{{ mail_php5_min_children }}'
  pm_min_spare_servers: 2
  pm_max_spare_servers: 10
  pm_start_servers: 2
  php_value:
    post_max_size: '{{ mail_upload_size }}'
    upload_max_filesize: '{{ mail_upload_size }}'

autoconfig_nginx_server:
  by_role: 'le90nx.mailweb autoconfig'
  enabled: True
  default: False
  listen: ['80','[::]:80']
  ssl: False
  type: 'default'
  name: "{{ mailweb_domain_autoconfig }}"
  root: '/srv/www/sites/autoconfig/public'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
