---

dependencies:

  - role: debops.secret

#  - role: le9i0nx.mailweb
  - role: debops.php5
    php5_packages: [ 'php5-mysql','php5' ]
#    php5_pools: [ '{{ postfixadmin_php5_pool }}' ]
#    when: postfixadmin_dependencies is defined and postfixadmin_dependencies
#    tags: [ 'mysql', 'postfixadmin' ]

  - role: debops.nginx
#    nginx_servers: [ '{{ postfixadmin_nginx_server }}' ]
#    nginx_upstreams: [ '{{ postfixadmin_nginx_upstream_php5 }}' ]
#    when: postfixadmin_dependencies is defined and postfixadmin_dependencies
#    tags: [ 'mysql', 'postfixadmin', 'nginx' ]
#
#galaxy_info:
#  author: 'Maciej Delmanowski'
#  description: 'Install and configure PHPMyAdmin on a MySQL database server'
#  company: 'DebOps'
#  license: 'GNU General Public License v3'
#  min_ansible_version: '1.7.0'
#  platforms:
#  - name: Ubuntu
#    versions:
#    - precise
#    - quantal
#    - raring
#    - saucy
#    - trusty
#  - name: Debian
#    versions:
#    - wheezy
#    - jessie
#  categories:
#  - 'database:sql'
#  - 'system'
#
#ansigenome_info:
#  github_url: "https://github.com/debops/ansible-phpmyadmin"
#  git_branch: "master"
#  galaxy_id: "1587"
#
#  travis: True
#
#  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'
#
#  authors:
#    - name:  'Maciej Delmanowski'
#      url: ''
#      email: 'drybjed@gmail.com'
#      twitter: 'drybjed'
#      github: 'drybjed'
#
#  synopsis: |
#    This role installs [PHPMyAdmin](http://www.phpmyadmin.net/) interface for
#    MySQL database. At the moment it is designed to manage only a database on
#    `localhost`, and is usually enabled by `debops.mysql` role itself in
#    a specifically written play. In the future it will be redesigned as
#    a standalone installation when secure access to remote databases is
#    available.
#
