---

dependencies:

  - role: debops.secret

  - role: debops.rsyslog
    rsyslog_pools: [ '{{ rsyslog_pool_dovecot }}' ]
    rsyslog_pool_dovecot:
        enabled: True
        name: '01-dovecot'
        options: |
            $template DynFileErr,"/var/log/%HOSTNAME%/dovecot/%$YEAR%.%$MONTH%.%$DAY%.err"
            if $programname == "dovecot" and $syslogfacility-text == "mail" and $syslogseverity-text == "err" then ?DynFileErr
            & stop

            $template DynFileDovecot,"/var/log/%HOSTNAME%/dovecot/%$YEAR%.%$MONTH%.%$DAY%.log"
            if $programname == "dovecot" then ?DynFileDovecot
            & stop

            $template DynFileImap,"/var/log/%HOSTNAME%/dovecot/%$YEAR%.%$MONTH%.%$DAY%.imap"
            if $programname == "imap" then ?DynFileImap
            & stop


  - role: debops.ferm
    tags: [ 'depend::ferm', 'depend::ferm:dovecot', 'depend-of::dovecot', 'type::dependency' ]
    ferm_dependent_rules: '{{ dovecot__ferm_dependent_rules }}'

