---

- name: Add hp repo key
  apt_key:
    data: "{{ lookup('file', 'hpPublicKey2048_key1.pub') }}"
#    url: 'http://downloads.linux.hp.com/SDR/repo/mcp/GPG-KEY-mcp'
    state: 'present'
  when: ansible_distribution == 'Ubuntu'


- name: Add hp repo
  apt_repository:
    repo: 'deb http://downloads.linux.hp.com/SDR/repo/mcp trusty/current non-free'
    state: 'present'
  when: ansible_distribution == 'Ubuntu'

- name: update list packages
  apt: update_cache=yes cache_valid_time=86400

- name: Install hp-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: hp_packages
  when: (hp_packages is defined and hp_packages)

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
