---

- name: Install postfixadmin packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: postfixadmin_packages
  when: (postfixadmin_packages is defined and postfixadmin_packages)

- name: configure postfixadmin
  template:
    src:    '{{item.src}}'
    dest:   '{{item.dest}}'
    owner:  'root'
    group:  '{{item.group | default("root") }}'
    mode:   '{{item.mode | default("0444") }}'
    backup: 'yes'
  with_items:
    - { src: 'etc/postfixadmin/config.inc.php.j2', dest: '/etc/postfixadmin/config.inc.php' }
    - { src: 'etc/postfixadmin/dbconfig.inc.php.j2', dest: '/etc/postfixadmin/dbconfig.inc.php', group: 'www-data' , mode: '0440' }
    - { src: 'etc/dbconfig-common/postfixadmin.conf.j2', dest: '/etc/dbconfig-common/postfixadmin.conf', mode: '0600' }
    - { src: 'etc/sudoers.d/01_mail.j2', dest: '/etc/sudoers.d/01_mail', mode: '0440' }
#    - { src: 'usr/local/bin/mysql-alias_mpautina-update.php.j2', dest: '/usr/local/bin/mysql-alias_mpautina-update.php', mode: '0555' }
    - { src: 'usr/local/bin/postfixadmin-mailbox-postcreation.sh.j2', dest: '/usr/local/bin/postfixadmin-mailbox-postcreation.sh', mode: '0555' }
    - { src: 'usr/local/bin/postfixadmin-mailbox-postdeletion.sh.j2', dest: '/usr/local/bin/postfixadmin-mailbox-postdeletion.sh', mode: '0555' }

- name: Create directories
  file:
    path:   '{{ item.path }}'
    state:  '{{ item.state  | default("directory") }}'
    owner:  '{{ item.owner  | default("root") }}'
    group:  '{{ item.group  | default("root") }}'
    mode:   '{{ item.mode   | default("0755") }}'
  with_items:
#  with_flattened:
    - { path: '/var/mail/deleted' , owner: 'mail' , group: 'mail' }
  when: (item.path is defined and item.path)
#
- name: Create database for postfixadmin
  mysql_db:
    name:   '{{ postfixadmin_control_database | default("postfixadmin") }}'
    state:  'present'
  register: postfixadmin_database

- name: copy postfixadmin schema
  copy:
    src:    '{{item.src}}'
    dest:   '{{item.dest}}'
    owner:  '{{ item.owner | default("root") }}'
    group:  '{{ item.group | default("root") }}'
    mode:   '{{ item.mode | default("0755") }}'
  with_items:
    - { src: 'postfixadmin-schema.sql', dest: '/etc/postfixadmin/postfixadmin-schema.sql' , mode: '0400' }
  register: postfixadmin_database

- name: Create db schema postfixadmin
  mysql_db:
    name:     '{{ postfixadmin_control_database | default("postfixadmin") }}'
    state:    'import'
    target:   '/etc/postfixadmin/postfixadmin-schema.sql'
  when: postfixadmin_database is defined and postfixadmin_database.changed == True

- name: Create postfixadmin control user
  mysql_user:
    name:     '{{ postfixadmin_control_user | default("postfixadmin") }}'
    state:    'present'
    password: '{{ postfixadmin_control_password }}'
    priv:     '{{ postfixadmin_control_database | default("postfixadmin") }}.*:ALL'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
