---

lcsh_challengesdir: /srv/www/sites/acme/public/.well-known/acme-challenge/
#lcsh_acme_api: https://acme-staging.api.letsencrypt.org/directory
lcsh_contactemail: hostmaster@info74.ru
lcsh_domains_info74_ru: "{{ mail_domain }} + {{ lcsh_domains_mpautina_ru }}"
lcsh_domains_mpautina_ru:
  - {domain: 'mpautina.ru',ou: 'mpautina'}

lcsh_domains: |
  {% for item in lcsh_domains_info74_ru %}mail.{{ item.domain }} smtp.{{ item.domain }} imap.{{ item.domain }} pop3.{{ item.domain }} {% endfor %}

lcsh_deploy_cert: |
  mkdir -p /etc/nginx/ssl/${DOMAIN}
  cp "${KEYFILE}" "${CERTFILE}" "${FULLCHAINFILE}" "${CHAINFILE}" /etc/nginx/ssl/${DOMAIN}
  chown root:root /etc/nginx/ssl/${DOMAIN}/*
  chmod 600 /etc/nginx/ssl/${DOMAIN}/privkey.pem
  chmod 644 /etc/nginx/ssl/${DOMAIN}/cert.pem
  chmod 644 /etc/nginx/ssl/${DOMAIN}/chain.pem
  chmod 644 /etc/nginx/ssl/${DOMAIN}/fullchain.pem

  mkdir -p /etc/dovecot/ssl/${DOMAIN}
  cp "${KEYFILE}" "${CERTFILE}" "${FULLCHAINFILE}" "${CHAINFILE}" /etc/dovecot/ssl/${DOMAIN}
  chown root:root /etc/dovecot/ssl/${DOMAIN}/*
  chmod 600 /etc/dovecot/ssl/${DOMAIN}/privkey.pem
  chmod 644 /etc/dovecot/ssl/${DOMAIN}/cert.pem
  chmod 644 /etc/dovecot/ssl/${DOMAIN}/chain.pem
  chmod 644 /etc/dovecot/ssl/${DOMAIN}/fullchain.pem

  mkdir -p /etc/exim4/ssl/${DOMAIN}
  cp "${KEYFILE}" "${CERTFILE}" "${FULLCHAINFILE}" "${CHAINFILE}" /etc/exim4/ssl/${DOMAIN}
  chown root:Debian-exim -R /etc/exim4/ssl
  chmod 640 /etc/exim4/ssl/${DOMAIN}/privkey.pem
  chmod 644 /etc/exim4/ssl/${DOMAIN}/cert.pem
  chmod 644 /etc/exim4/ssl/${DOMAIN}/chain.pem
  chmod 644 /etc/exim4/ssl/${DOMAIN}/fullchain.pem

  /etc/init.d/nginx reload
  service dovecot restart
  /etc/init.d/exim4 reload

## vim: ft=yaml:foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
