---

bacula__conf_dir:
  name: 'test'
  name_ansible: "dir_name_ansible"
  ip:
    - "127.0.0.1"


# Password set on client, saved in secrets
bacula__gen_client_password: '{{ lookup("password", secret + "/bacula/client/" + ansible_fqdn + "/password chars=ascii_letters,hexdigits length=" + bacula__gen_password_length  ) }}'

bacula__gen_sd_password: '{{ lookup("password", secret + "/bacula/sd/" + bacula__conf_sd.name_ansible + "/password chars=ascii_letters,hexdigits length=" + bacula__gen_password_length  ) }}'

# # Length of the password
bacula__gen_password_length: '57'

# .. envvar:: bacula__ferm_dependent_rules
#
# Configuration for ``iptables`` firewall managed by ``ferm``.
bacula_storage__ferm__dependent_rules:

  - type: 'accept'
    dport: [ 'bacula-sd' ]
    protocol: [ 'tcp','udp' ]
    role: 'le9i0nx.bacula_storage'
    accept_any: True

bacula_storage__apt__repositories:

  - {repo: 'deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse', mode: "0444" }
  - {repo: 'deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse', mode: "0444" }
  - {repo: 'deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe multiverse', mode: "0444" }
  - {repo: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse', mode: "0444" }

bacula_storage__apt_preferences__dependent_list:

  - package: 'bacula-*'
    by_role: 'le9i0nx.bacula_storage'
    priority: '50'
    pin: 'release xenial'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
