---
ferm_ansible_controllers:  "{{admin_allow_pool +
  ['0.0.0.0/0']}}"

#ntp
ntp_timezone: 'Asia/Yekaterinburg'
ntp_listen: ['localhost']
ntp_servers: [ '192.168.0.7' ]

#ssh
sshd__ferm_limit: 'false'
sshd__PasswordAuthentication: 'yes'
sshd__permit_root_login: 'yes'

# smartd
smartd_mail: 'admins@mpautina.ru'
smartd_disks:
  - {disk: '/dev/sda', sub: '', s_hour: '01', l_dow: '6', l_hour: '02'  }
  - {disk: '/dev/sdb', sub: '', s_hour: '01', l_dow: '6', l_hour: '02'  }

#nagios_nrpe_server_config
nagios_nrpe_server_apt_packages_group: []
icinga__client_hostgroups_group:
  - "nrpe_raid"
  - "nrpe_mio_sda"
  - "nrpe_mio_sdb"
  - "1c"

icinga__client_hostgroups_default:
  - "ssh"
  - "nrpe"
  - "nrpe_space"
  - "nrpe_mem"
  - "nrpe_traffic"
  - "nrpe_ntpdate"

nagios_nrpe_server_commands_group:
  - {name: "check_raid", plugin: "check_raid", sudo: true }

## vim: ft=yaml:foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
