---
freedns_afraid_dynamic_id: "azFqM1BBdVFkR0tWdUljc3BzZThFc2J4OjExOTA3ODk5"
le9i0nx.install.it7_hosting: True
#tinc_host_addr: [ '172.16.35.1/24' ]
ifupdown_ignore_static: True
#tinc
tinc_network: 'mesh0'
tinc_inventory_hosts: '{{ groups.homes }}'
tinc_interface: '{{ tinc_network }}'
tinc_connection_type: 'ipv4ll'
tinc_ifupdown_interface:
  - iface: '{{ tinc_interface }}'
    type: 'interface'
    inet: '{{ tinc_connection_type }}'
    auto: '{{ tinc_interface_auto }}'
    force: True
