---
nsswitch_config:
  passwd:
    - compat
    - ldap
    - winbind
  group:
    - compat
    - ldap
    - winbind
  shadow:
    - compat
  hosts:
    - files
    - dns
  networks:
    - files
  protocols:
    - db
    - files
  services:
    - db
    - files
  ethers:
    - db
    - files
  rpc:
    - db
    - files
  netgroup:
    - nis

role__nss_pam_ldap:
  host: "127.0.0.1"
  base: "{{ samba__ldap_suffix }}"

auth_ldap_conf: False
auth_nslcd_conf: False

slapd__domain: 'rugion.ru'

slapd__syncrepl:
  - rid: '000'
    provider: '{{ slapd__default_syncprov_provider }}'
    binddn: '{{ slapd__basedn_admin }}'
    credentials: '{{ lookup("password", slapd__basedn_admin_password + " length=" + slapd__password_length) }}'
    searchbase: '{{ slapd__basedn }}'

slapd__ldap_access_control_list_default:

  - |
    to attrs=userPassword,shadowLastChange,sambaNTPassword,sambaLMPassword
      by self write
      by anonymous auth
      by * none

  - |
    to *
      by self write
      by anonymous read
      by * read

slapd__ldap_index:

  - 'objectClass eq'
  - 'cn pres,sub,eq'
  - 'gn eq,pres'
  - 'sn eq,pres'
  - 'uidNumber eq'
  - 'uniqueMember eq'
  - 'gidNumber eq'
  - 'memberUid eq'
  - 'sambaSID eq'
  - 'sambaGroupType eq'
  - 'sambaSIDList eq'
  - 'host eq'
  - 'entryCSN eq'
  - 'entryUUID eq'
  - 'telephoneNumber pres,sub,eq'
  - 'mail eq,subinitial'
  - 'uid pres,sub,eq'
  - 'displayName pres,sub,eq'

slapd__ldap_schema:
  - 'core'
  - 'cosine'
  - 'inetorgperson'
  - 'nis'
  - 'misc'
  - 'samba3'

icinga__client_hostgroups_ldap:
    - 'ldap-rugion-ru'
