---

ntp__daemon: 'systemd-timesyncd'
# syncthing
syncthing__dependencies_ferm: True
device_x:
  - id: "6BZW7ME-VSKBWJX-OCALJTF-W73GAZB-YHS4VWB-PKMQHNB-GFDQYJY-4HZDMA4"
    name: "x"

device_y:
  - id: "5JEVGUF-5YSMIKQ-3D5MK3W-WRO3RFW-SFN2ZGS-4CUKZ3P-CVLDUBH-KRGIWQP"
    name: "y"

role_syncthing_data:
  folders:
    - inventory_hosts: '{{ groups.pve }}'
      path: '/var/lib/vz/template/iso/'
      id: 'vz_iso'
      devices_del:
        - "{{ device_x }}"
        - "{{ device_y }}"
    - inventory_hosts: '{{ groups.pve }}'
      path: '/var/lib/vz/template/cache/'
      id: 'vz_template'
      devices_del:
        - "{{ device_x }}"
        - "{{ device_y }}"

#tinc
tinc__connect_to_mesh_pve: '{{ tinc__inventory_hosts_mesh_pve }}'
tinc__inventory_hosts_mesh_pve: '{{ (groups.pve if groups.pve|d() else []) | difference([ tinc__hostname ]) }}'
tinc__default_networks: []
tinc__inventory_groups: ['pve']
tinc__inventory_hosts: '{{ groups.pve if groups.pve|d() else [] }}'
tinc__networks: [ '{{ tinc__network_mesh_pve }}' ]
tinc__host_addresses: '{{ tinc__host_addresses_ip }}'
tinc__interface_mesh_pve: 'mesh_pve'
tinc__interface_mesh0: '{{ tinc__interface_mesh_pve }}'
tinc__exclude_bridge_mesh0: []
tinc__network_mesh_pve:
  name: '{{ tinc__interface_mesh_pve }}'
  interface: '{{ tinc__interface_mesh_pve }}'
  hwaddr: ''
  bridge: ''
  link_type: 'static'
  boot: True
  port: '655'
  mlock: True
  chroot: True
  allow: ''
  user: '{{ tinc__user }}'
  tinc_exclude_addresses: '{{ tinc__exclude_addresses_mesh0 }}'
  tinc_options:
    Mode: 'switch'
    DeviceType: 'tap'
    Cipher: 'aes-256-cbc'
    Digest: 'SHA512'
    ConnectTo: '{{ tinc__connect_to_mesh_pve }}'

tinc__ifupdown_interface:
  - iface: '{{ tinc__interface_mesh_pve }}'
    type: 'interface'
    inet: 'static'
    auto: True
    addresses: '{{ tinc_host_addr }}'

#ssh
sshd__permit_root_login: 'yes'
sshd__password_authentication: 'yes'

# ferm
ferm_enabled: False
ferm__enabled: False

#hostname
hostname_hosts:
    - { ip: "127.0.0.1", name: "localhost" }

hostname_hosts_static: "[{% if ansible_mesh_pve is defined %}{ u'ip': '{{ ansible_mesh_pve.ipv4.address }}', u'name': '{{ ansible_hostname}}{% if ansible_hostname != inventory_hostname %}\t{{inventory_hostname}}{% endif %}' }{% endif %} ]"
hostname_hosts_add: "{{ hostname_hosts_static }}"

#apt
apt_base_packages: [ 'ed', 'python', 'python-apt', 'lsb-release', 'make', 'sudo', 'gnupg-curl',
                     'git', 'wget', 'curl', 'rsync', 'bridge-utils',
                     'openssh-server', 'bsdutils', 'python-pycurl', 'python-httplib2',
                     'apt-transport-https', 'acl', 'python-pip' ]

#nagios_nrpe_server_config
nagios_nrpe_server_commands_group:
  - {name: "check_apt", plugin: "check_apt", args: "-c trusty-updates"}
  - {name: "check_raid", plugin: "check_raid", sudo: true }

icinga__client_hostgroups_group:
  - "nrpe_raid"
  - "proxmox"
  - "nrpe_mio_sda"
  - "nrpe_mio_sdb"

#bacula
bacula__conf_client_job_group:
  - {name: "vz_dump", JobDefs: "vz_dumpDefs", Schedule: "Daily_0" }
bacula__conf_client_jobDefs_group:
  - {name: "vz_dumpDefs", Schedule: "Daily_0", FileSet: "vz_dump-set" }
bacula__conf_client_FileSet_group:
  - {name: "vz_dump-set", File: [ "/var/lib/vz/dump" ] }

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
